### ISSUE TITLE
CBMC PR Tracking

### ISSUE THREAD

**Issue by dougch** [aws/aws-encryption-sdk-c#456]
Tracking/Prioritizing ticket for the [CBMC](https://github.com/aws/aws-encryption-sdk-c/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+label%3Acbmc) PRs.

- [x] [Cbmc to master](454)
- [x] [Aws cryptosdk materials proofs - Part 1 ](443)
- [x] [Aws cryptosdk edk proofs ](442)
- [x] [Aws cryptosdk genrandom ](441)
- [x] [Proof for aws_cryptosdk_rsa_decrypt ](438)
- [x] [Proof for aws_cryptosdk_rsa_encrypt ](437)
- [x] [Proofs for aws_cryptosdk_aes_gcm_{encrypt,decrypt} ](436)
- [x] [aws_cryptosdk_hkdf and derive_key ](435)
- [x] [Aws cryptosdk {sign verify} header ](434)
- [x] [aws_cryptosdk_enc_ctx_clone proof ](428)
- [x] [Proof for aws_cryptosdk_enc_ctx_deserialize ](427)
- [x] [Aws cryptosdk enc ctx size CBMC proof and cleanup ](423)
- [x] [Aws cryptosdk enc ctx serialize CBMC proof and fixup ](422)
- [x] [Proofs for keyring_trace module eq, clear and clean_up functions ](420)
- [x] [Proofs for the add record functions of keyring trace module ](419)
- [x] [Proof harnesses for aws_cryptosdk_sig_verify_{start, finish} ](418)

**Comment by dougch** [comment]
First merge [pr/1479](https://github.com/awslabs/s2n/pull/1479)
